---
- name: Create service from template
  template: 
    src: templates/service.j2
    dest: /etc/systemd/system/{{service_name}}
    mode: 0644

- name: Create timer from template
  template:
    src: templates/timer.j2
    dest: /etc/systemd/system/{{timer_name}}
    mode: 0644

- name: run and enable timer
  systemd:
    name: "{{ timer_name }}"
    state: started
    enabled: true
    daemon_reload: true

- name: run backup first time so timer will have first record
  systemd:
    name: "{{ service_name }}"
    state: started
    enabled: true
...